version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27028:27017"

  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MONGO_DB_URL: ${MONGO_DB_URL}
    volumes:
      - .:/app
    ports:
      - "8051:8000"
    depends_on:
      - mongodb

volumes:
  mongo-data:
